apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: ingress-controller
  name: default-backend-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: default-backend-deployment
    spec:
      containers:
        - name: defaultbackend
          image: 'gcr.io/google_containers/defaultbackend:1.0'
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "20Mi"
              cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  namespace: ingress-controller
  name: default-backend-service
  labels:
    name: default-backend-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: default-backend-deployment
  type: ClusterIP
